### ISSUE TITLE
cant load v3 live2d ...

### ISSUE THREAD

**Issue by wang2956** [Arkueid/live2d-py#1]
window python
cmd: ...live2d-py-main\example\main_pygame.py

from .live2d import *
ImportError: DLL load failed while importing live2d: %1

**Comment by Arkueid** [comment]
The Live2D library stored in this repository is compatible only with Python 3.10.11 (Win32). For users of Python (Win64) or other Python versions, please compile the source code accordingly.
You can download the target Python (3.10.11, Win32) venv from [here](https://github.com/Arkueid/live2d-py/releases/download/v0.1.1-alpha/venv.zip).

**Comment by Arkueid** [comment]
> Hello, I suggest you drop support for SDK 2.0. After all it is outdated. And there are some articles on the official website that teach people to upgrade their models🤔. (I think it should be the biggest impediment to going full X64) 大佬好，建议放弃对Cubism 2.0 Model的支持, 已经是2014年的老东西了，并且官网有说转换2.0到更高版本的方法🤔（我想它应该是全面推进X64的最大阻碍）
> 
> By the way is 5.0 supported? 顺便问一下5.0支持不？
> 
> Also, hopefully the distro builds will be bumped up a bit, the performance improvements in 3.11 are very helpful for live2d rendering. 另外期望将release构建版本提升一些，3.11的性能提升对live2d渲染挺有帮助的
> 
> I'm getting some errors with my own build of 3.12-x64, so far it's not fixed 😅. 我这边自己构建3.12-x64，但build的时候乱码报错，到现在还没解决😅

---
Version for Python 3.12-x64：Version for Python 3.12-x64: [live2d-py_v3_python3.12_win64.zip](https://github.com/Arkueid/live2d-py/releases/download/v0.1.1-alpha/live2d-py_v3_python3.12_win64.zip).

The Cubism SDK version 5.0 doesn’t have significant changes and should be compatible with models from versions 4.0 and 3.0.

Future updates of version 3 will be released for x64 only. It seems that many of the latest libraries do not support win32 Python anymore, <del>x86 out</del>.

I haven’t given up on version 2.0 yet; I'll look into methods for upgrading 2.0 to higher versions.

By the way, would you like to provide the build error information in detail?

---

Python 3.12-x64 的版本：[live2d-py_v3_python3.12_win64.zip](https://github.com/Arkueid/live2d-py/releases/download/v0.1.1-alpha/live2d-py_v3_python3.12_win64.zip)。

5.0 的 Cubism SDK 没有特别大的变化，应该兼容 4.0、3.0 的模型。

后续 v3 的更新以 x64 发布吧，貌似很多最新库也不支持 win32 的 Python，<del>x86 该淘汰了</del>。

暂时没有放弃 2.0 的想法，等我研究研究 2.0 转高版本的方法吧。

如果有时间的话可以提供一下完整的构建报错信息吗？

**Comment by Yunxi-awa** [comment]
根据官方文章，转高版本需要在Cubism Editor中实现，想在Python或C中实现应该是挺困难的。

因为我是x64 Python 所以用的是x64编译器，但即便换x86依然报错（我不是很熟悉C系，用java更多些
但看报错内容并结合搜索引擎，感觉可能是Github上的项目配置文件不是很完整？如果说错了就当没说了。。。

CMake配置是没问题的，但构建有问题
以下是VSC截图和报错信息，乱码内容是`此项目不包含配置和平台组合 Debug|x64`

![image](https://github.com/Arkueid/live2d-py/assets/130226803/aae127de-80a7-4cb5-a356-5080d30245c7)

```
[main] 正在生成文件夹: live2d-py 
[build] 正在启动生成
[proc] 执行命令: D:\VisualStudio\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build e:/Code/live2d-py/build --config Debug --target LAppModelWrapper -j 18 --
[build] 閫傜敤浜� .NET Framework MSBuild 鐗堟湰 17.10.4+10fbfbf2e
[build] 
[build] D:\VisualStudio\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(452,5): error MSB8013: 姝ら」鐩�涓嶅寘鍚�閰嶇疆鍜屽钩鍙扮粍鍚� Debug|x64銆� [E:\Code\live2d-py\build\ZERO_CHECK.vcxproj]
[proc] 命令“D:\VisualStudio\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe --build e:/Code/live2d-py/build --config Debug --target LAppModelWrapper -j 18 --”已退出，代码为 1
[driver] 生成完毕: 00:00:00.361
[build] 生成已完成，退出代码为 1
[cpptools] 生成的生成配置不包含活动生成配置。对 CMAKE_BUILD_TYPE 使用 "Release" 而不是 "Debug"，以确保可以找到 IntelliSense 配置

```

**Comment by Yunxi-awa** [comment]
![image](https://github.com/Arkueid/live2d-py/assets/130226803/c42a39c9-5210-4e90-a60b-ed17fdb31296)
问题已经解决，我只是将Debug模式切换到了Release模式😅
另外报告一个大小写问题：
![image](https://github.com/Arkueid/live2d-py/assets/130226803/fc68da61-6cf2-4fd5-9665-5627b5a3f3ea)
