### ISSUE TITLE
请问能否支持不透明度的选项

### ISSUE THREAD

**Issue by xiaosuyyds** [Arkueid/live2d-py#10]
如题，有一些模型可能会有一些部件通过在动画中设置不透明度来控制的显示和消失的，但是似乎live2d-py中无法设置部件的透明度，所以请问能否支持设置不透明度的选项，最好也能在python中也能直接设置某个部件的不透明度

在VTS中是这样的
![image](https://github.com/user-attachments/assets/befbcfbd-27e5-47c0-b2fd-63d42cdf12f6)

在live2d-py中是这样的
![image](https://github.com/user-attachments/assets/a386ebf4-2057-412a-a47f-47a373510984)

**Comment by Arkueid** [comment]
添加了`Part`透明度控制

```python
class LAppModel:
    ...

    def GetPartCount() -> int:
        pass

    def GetPartId(index: int) -> str:
        pass

    def GetPartIds() -> list[str]:
        pass

    def SetPartOpacity(index: int, opacity: float) -> None:
        pass
```

用例： 

```python
log.Debug(f"Part Count: {model.GetPartCount()}")
#  获取模型的 part id 列表（字符串列表）
partIds = model.GetPartIds()
log.Debug(f"Part Ids: {partIds}")
# 通过 part id 在列表中的 index 来设置其透明度
model.SetPartOpacity(partIds.index("PartHairBack"), 0.5)

**Comment by xiaosuyyds** [comment]
> 添加了`Part`透明度控制
> 
> ```python
> class LAppModel:
>     ...
> 
>     def GetPartCount() -> int:
>         pass
> 
>     def GetPartId(index: int) -> str:
>         pass
> 
>     def GetPartIds() -> list[str]:
>         pass
> 
>     def SetPartOpacity(index: int, opacity: float) -> None:
>         pass
> ```
> 
> 用例：
> 
> ```python
> log.Debug(f"Part Count: {model.GetPartCount()}")
> #  获取模型的 part id 列表（字符串列表）
> partIds = model.GetPartIds()
> log.Debug(f"Part Ids: {partIds}")
> # 通过 part id 在列表中的 index 来设置其透明度
> model.SetPartOpacity(partIds.index("PartHairBack"), 0.5)
> ```

感谢，昨天看到pr合并就已经用上了
