### ISSUE TITLE
pypi上没有同步0.2.3版本

### ISSUE THREAD

**Issue by LYSS-lz** [Arkueid/live2d-py#12]
1.麻烦问下，是还会有改动么？
2.因为最近对Bongo Cat Mver 这个软件感兴趣，就想用python尝试搞个类似的桌宠
或者Bongo Cat Mver一样的显示键盘鼠标操作的live2d展示软件
想请教下您，我直接用同样的模型（可能动作没有那么多，也没有嘴部的动作啥的），能否直接使用您这个库--live2d_py？示例里面的一些动作没有的话，应该也不影响吧？

**Comment by Arkueid** [comment]
> 1.麻烦问下，是还会有改动么？
之前因为版本号的问题没上传成功，pypi对版本要求比较严格（上传错了不能只能递增版本号），所以就没管了（之后再上传吧）。最新的还没发布release，0.2.3的版本在release里面，下载对应的whl安装。不过最稳妥的方式还是克隆之后编译，可以避免很多版本、32位、64位之类的问题。
> 2.因为最近对Bongo Cat Mver 这个软件感兴趣，就想用python尝试搞个类似的桌宠
> 或者Bongo Cat Mver一样的显示键盘鼠标操作的live2d展示软件
> 想请教下您，我直接用同样的模型（可能动作没有那么多，也没有嘴部的动作啥的），能否直接使用您这个库--live2d_py？示例里面的一些动作没有的话，应该也不影响吧？
动作没有没问题的，嘴型同步的部分如果报错也可以删掉。

**Comment by Arkueid** [comment]
> 1.麻烦问下，是还会有改动么？
之前因为版本号的问题没上传成功，pypi对版本要求比较严格（上传错了不能只能递增版本号），所以就没管了（之后再上传吧）。最新的还没发布release，0.2.3的版本在release里面，下载对应的whl安装。不过最稳妥的方式还是克隆之后编译，可以避免很多版本、32位、64位之类的问题。
> 2.因为最近对Bongo Cat Mver 这个软件感兴趣，就想用python尝试搞个类似的桌宠
> 或者Bongo Cat Mver一样的显示键盘鼠标操作的live2d展示软件
> 想请教下您，我直接用同样的模型（可能动作没有那么多，也没有嘴部的动作啥的），能否直接使用您这个库--live2d_py？示例里面的一些动作没有的话，应该也不影响吧？

动作没有没问题的，嘴型同步的部分如果报错也可以删掉。

**Comment by LYSS-lz** [comment]
好的好的，明白了，已经下载了whl文件，感谢。
