### ISSUE TITLE
对单独部位的控制

### ISSUE THREAD

**Issue by luckykevvv** [Arkueid/live2d-py#2]
您好，请问库是否支持对单独部位的控制，比如说眼睛的单独开关

**Comment by luckykevvv** [comment]
我读了一编您写的live2d-desktop, 似乎并没有对语言模型的输出进行tts处理并同步嘴型, 如果可以对单独部位控制，则可以根据响度区间来控制嘴型的开合程度以实现模拟说话。

**Comment by Arkueid** [comment]
口型同步目前集成在 `StartMotion`方法中，如果对应动作有音频，会通过音频数据同步嘴型。后续会添加对各个部位的参数控制。

**Comment by luckykevvv** [comment]
懂了，很抱歉我对live-2d的了解比较浅薄，请问在idle状态下可否根据输入的外部音频而不只是模型自带的音频来改变口型

**Comment by luckykevvv** [comment]
这是Haru模型的动作之一
                {
                    "File": "",
                    "Sound": "sounds/haru_normal_6.wav",
                    "Text": "233232323"
                },
调用没有对应动作json的motion貌似会导致错误并中断，这是正常的吗？

**Comment by Arkueid** [comment]
> 这是Haru模型的动作之一 { "File": "", "Sound": "sounds/haru_normal_6.wav", "Text": "233232323" }, 调用没有对应动作json的motion貌似会导致错误并中断，这是正常的吗？

不正常的，现在应该修好了。



> 我读了一编您写的live2d-desktop, 似乎并没有对语言模型的输出进行tts处理并同步嘴型, 如果可以对单独部位控制，则可以根据响度区间来控制嘴型的开合程度以实现模拟说话。

现在可以关闭内置的口型同步功能，直接通过`SetParameterValue`来控制嘴部开合。

**Comment by luckykevvv** [comment]
> > 这是Haru模型的动作之一 { "File": "", "Sound": "sounds/haru_normal_6.wav", "Text": "233232323" }, 调用没有对应动作json的motion貌似会导致错误并中断，这是正常的吗？
> 
> 不正常的，现在应该修好了。
> 
> > 我读了一编您写的live2d-desktop, 似乎并没有对语言模型的输出进行tts处理并同步嘴型, 如果可以对单独部位控制，则可以根据响度区间来控制嘴型的开合程度以实现模拟说话。
> 
> 现在可以关闭内置的口型同步功能，直接通过`SetParameterValue`来控制嘴部开合。

十分感谢您修复这个问题
