### ISSUE TITLE
实现模型part颜色改变

### ISSUE THREAD

**Issue by jahtim** [Arkueid/live2d-py#23]
如题，可以用核心中的这两种方法简单的添加get和set方法来获得和改变part的两种颜色系数，比如get输入：“PartEye”，返回(1.0,.1.0,1.0,1.0), set输入“PartEye”, 2.0, 1.0, 0.2, 1.0 ，实现单个part红色加重的效果

csmGetDrawableMultiplyColors  csmGetDrawableScreenColors 

这两种系数似乎是不同逻辑，按文档里说的，可能都可以用得上
Additive synthesis
𝑂𝑟𝑔𝑏 = 𝐷𝑟𝑔𝑏 + 𝑆𝑟𝑔𝑏
𝑂𝑎 = 𝐷𝑎
Multiplicative synthesis
𝑂𝑟𝑔𝑏 = 𝐷𝑟𝑔𝑏 × (1 − 𝑆𝑎) + 𝑆𝑟𝑔𝑏 × 𝐷𝑟𝑔𝑏
𝑂𝑎 = 𝐷𝑎

![20241205154207](https://github.com/user-attachments/assets/e6da3cd3-2b64-4be5-ad38-73dafa881209)

**Comment by Arkueid** [comment]
```python
# 大模型的说法是 滤色模式 ？应该是吧
# 假设 255 为最大灰度级
# 原色和屏幕色取反并相乘，再取反
# 以红色通道为例：r = 255 - (255 - 原色.r) * (255 - screenColor.r) / 255
# 通道数值越大，该通道颜色对最终结果的贡献越大，下面的调用即为突出蓝色的效果
model.SetPartScreenColor(pidx, .0, 0., 1.0, 1)

# 正片叠底
# r = multiplyColor.r * 原色.r / 255
# 下面即为仅保留蓝色通道的结果
model.SetPartMultiplyColor(pidx, .0, .0, 1., .9)
```
