### ISSUE TITLE
V3版本的__init__.py的from .live2d import *导入live2d.pyd报错，一直说找不到指定的模块

### ISSUE THREAD

**Issue by worm128** [Arkueid/live2d-py#28]
File "J:\ai\ai-code\桌宠\live2d-py\package\runtime\lib\site-packages\live2d\v3\__init__.py", line 2, in <module>
    from .live2d import *
ImportError: DLL load failed while importing live2d: 找不到指定的模块。

![图片](https://github.com/user-attachments/assets/7608ad56-2ae5-41a9-ad40-39297a47d908)

**Comment by Arkueid** [comment]
repo 中的 live2d.pyd 适用于 python 3.12.X win64，python 解释器版本不一致会导致错误。

使用其他版本的 python 需要安装对应版本的 live2d-py。

适用 python 3.10.X 的 live2d-py 是和 python 3.10.0 一起编译的，但是不知道什么原因，python 3.10 的部分子版本也不互通。

python 3.10.11 的 live2d-py 目前只能自行编译了。

**Comment by worm128** [comment]
我现在用的是live2d_py-0.3.0-cp310-cp310-win_amd64.whl，对应的是64位的python3.10.6，我是window11 64位系统，看whl文件应该是兼容的吧？

**Comment by Arkueid** [comment]
release 中的不行。先暂时用这个吧：3.10.10的 live2d.pyd，[live2d.zip](https://github.com/user-attachments/files/18245111/live2d.zip)

**Comment by worm128** [comment]
> release 中的不行。先暂时用这个吧：3.10.10的 live2d.pyd，[live2d.zip](https://github.com/user-attachments/files/18245111/live2d.zip)

好的，谢谢大佬

**Comment by worm128** [comment]
已测试成功运行，谢谢
![图片](https://github.com/user-attachments/assets/cb9825f0-d9cc-47d7-b1d5-817986934e25)
