### ISSUE TITLE
live2D的V2版本可以背景透明，但是V3版本不能背景透明

### ISSUE THREAD

**Issue by worm128** [Arkueid/live2d-py#30]
我用的是main_pyside6.py的例子
V2版本可以背景透明，但是V3版本不能背景透明
self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True) 这句透明在v2版本是生效的，v3就不生效了

我尝试设置这几个参数，都不能去掉白色的背景色
gl.glEnable(gl.GL_BLEND)
gl.glBlendFunc(gl.GL_SRC_ALPHA, gl.GL_ONE_MINUS_SRC_ALPHA)

format = QSurfaceFormat()
format.setAlphaBufferSize(8)
QSurfaceFormat.setDefaultFormat(format)

gl.glClearColor(0.0, 0.0, 0.0, 0.0)

![图片](https://github.com/user-attachments/assets/33760f1c-604e-4d94-a631-8b1c8777b9a8)

**Comment by Arkueid** [comment]
paintGL 中的 gl.glClear 换成 live2d.clearBuffer。

**Comment by worm128** [comment]
> clearBuffer

paintGL中改成这个：gl.clearBuffer(gl.GL_COLOR_BUFFER_BIT)
产生错误：
AttributeError: Error calling Python override of QOpenGLWidget::paintGL(): module 'OpenGL.GL' has no attribute 'clearBuffer'

**Comment by worm128** [comment]
> paintGL 中的 gl.glClear 换成 live2d.clearBuffer。

    def paintGL(self) -> None:
        gl.glClearColor(0.0, 0.0, 0.0, 0.0)
        gl.glClear(gl.GL_COLOR_BUFFER_BIT)
        
       加了gl.glClearColor(0.0, 0.0, 0.0, 0.0)这个可以透明，但是窗口无法拖拽了

**Comment by worm128** [comment]
def paintGL(self) -> None:
        live2d.clearBuffer()
live2d.clearBuffer()也是可以透明了，但是不能拖拽窗口了

**Comment by Arkueid** [comment]
看看同目录下生成的 screenshot.png

**Comment by worm128** [comment]
screenshot.png 看起来是透明的，只是位置不对

![screenshot](https://github.com/user-attachments/assets/c5d70bdf-be9a-4050-8e89-c17c36a9b7e1)

**Comment by Arkueid** [comment]
系统缩放的问题， 问题在于
```
def isInL2DArea(self, click_x, click_y):
        h = self.height()
        alpha = gl.glReadPixels(click_x, h - click_y, 1, 1, gl.GL_RGBA, gl.GL_UNSIGNED_BYTE)[3]
        return alpha > 0
```

 来自 #16 的解决方法
需要乘上windows系统的缩放因子
click_x * systemScale,
(h - click_y) * systemScale

**Comment by worm128** [comment]
可以了，加上了获取系统缩放因子的方法，谢谢大佬指点，感谢回复。
def __init__(self) -> None:
        super().__init__()
        self.system_scale = self.get_system_scale_factor()

def get_system_scale_factor(self):
        # 获取主屏幕
        screen: QScreen = QGuiApplication.primaryScreen()
        # 获取设备像素比率（DPR），即缩放因子
        scale_factor = screen.devicePixelRatio()
        return scale_factor

def isInL2DArea(self, click_x, click_y):
        h = self.height()
        alpha = gl.glReadPixels(click_x * self.system_scale, (h - click_y) * self.system_scale, 1, 1, gl.GL_RGBA, gl.GL_UNSIGNED_BYTE)[3]
        return alpha > 0

![图片](https://github.com/user-attachments/assets/b1214c44-6522-4132-8e4b-2054b259d3e9)

**Comment by gyl1314** [comment]
大哥们，可以帮小地看看吗，我看到你们的对话后，这样设置了，一个gl和live2d。clearbuff（）都是显示黑色窗口，

![Image](https://github.com/user-attachments/assets/5250f979-b5e6-43f9-9f3d-95f139c63416)

**Comment by Arkueid** [comment]
是把 Live2DWidget 作为 MainWindow 的 centralWidget 吗？如果是，MainWindow 里有设置 `setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)` 吗👀

> 大哥们，可以帮小地看看吗，我看到你们的对话后，这样设置了，一个gl和live2d。clearbuff（）都是显示黑色窗口，
> 
> ![Image](https://github.com/user-attachments/assets/5250f979-b5e6-43f9-9f3d-95f139c63416)

**Comment by gyl1314** [comment]
有设置的

![Image](https://github.com/user-attachments/assets/ab49400a-c138-4398-9bb2-96bb160d665b)

**Comment by gyl1314** [comment]
> 是把 Live2DWidget 作为 MainWindow 的 centralWidget 吗？如果是，MainWindow 里有设置 吗 👀`setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)`
> 
> > 大哥们，可以帮小地看看吗，我看到你们的对话后，这样设置了，一个gl和live2d。clearbuff（）都是显示黑色窗口，
> > ![Image](https://github.com/user-attachments/assets/5250f979-b5e6-43f9-9f3d-95f139c63416)

有设置的

**Comment by gyl1314** [comment]
> > 是把 Live2DWidget 作为 MainWindow 的 centralWidget 吗？如果是，MainWindow 里有设置 吗 👀`setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)`
> > > 大哥们，可以帮小地看看吗，我看到你们的对话后，这样设置了，一个gl和live2d。clearbuff（）都是显示黑色窗口，
> > > ![Image](https://github.com/user-attachments/assets/5250f979-b5e6-43f9-9f3d-95f139c63416)
> 
> 有设置的

![Image](https://github.com/user-attachments/assets/6aad365a-6516-4ef1-8979-5ad3192abf88)

**Comment by Arkueid** [comment]
方便发一下完整代码吗

**Comment by gyl1314** [comment]
> 方便发一下完整代码吗

方便方便，

import os
import sys
from typing import Optional

from OpenGL.raw.GL.VERSION.GL_1_0 import glEnable, GL_BLEND, glBlendFunc, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, \
    glClearColor, glClear, GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT, glViewport
from PySide6.QtCore import Qt, QTimer, QPoint
from PySide6.QtGui import QSurfaceFormat, QMouseEvent
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import QApplication, QMainWindow
import live2d.v3 as live2d
from live2d.v3.params import StandardParams



class Live2DWidget(QOpenGLWidget):
    def __init__(self, model_path: str):
        super().__init__()
        self.model_path = os.path.normpath(model_path)
        self.model: Optional[live2d.LAppModel] = None
        self.last_pos = QPoint()
        self.setAutoFillBackground(False)  # 在Live2DWidget构造函数中添加


        # OpenGL 高级配置

        fmt = QSurfaceFormat()
        fmt.setAlphaBufferSize(0)
        fmt.setSamples(4)
        self.setFormat(fmt)

        # 60FPS 定时器
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.update)
        self.timer.start(16)

    def initializeGL(self):
        # 核心透明通道初始化[6,7](@ref)
        glEnable(GL_BLEND)
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
        # glClearColor(1.0, 0.0, 0.0, 0.0)
        # live2d.clearBuffer()

        # Live2D 初始化
        live2d.init()
        live2d.glewInit()

        # 加载模型（增加异常处理）
        try:
            self.model = live2d.LAppModel()
            self.model.LoadModelJson(self.model_path)
            # 根据模型发布者或者模型 XXX.cdi3.json 中可查找到水印对应的参数 id

            # 假设查找到的模型参数 id 为 Param261，假设值为 0 表示显示水印，值为 1 表示消失
            self.model.SetParameterValue("Param14", 1, 1)
            # print(f"Part Count: {self.model.GetPartCount()}")
            # # 获取 part 名称的字符串数组
            # partIds = self.model.GetPartIds()
            # print(f"Part Ids: {partIds}")
            # # 设置部件 PartHairBack 的透明度为 50%
            # self.model.SetPartOpacity(partIds.index("PartHairBack"), 0.5)
            # self.model.SetPartOpacity(partIds.index("PartHairBack"), 0.5)
            self.model.Resize(self.width(), self.height())
        except Exception as e:
            print(f"模型加载失败: {str(e)}")
            QApplication.instance().quit()

    def paintGL(self):

        # glClearColor(0.0, 0.0, 0.0, 0.0)
        # glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)  # 关键修复点[1,6](@ref)
        # glClear(GL_COLOR_BUFFER_BIT)
        live2d.clearBuffer()
        if self.model:
            self.model.Update()
            self.model.Draw()

    def resizeGL(self, w: int, h: int):
        glViewport(0, 0, w, h)
        if self.model:
            self.model.Resize(w, h)
class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Live2D透明窗口")

        # 配置主窗口透明
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        self.setWindowFlag(Qt.WindowType.FramelessWindowHint)
        # self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)

        self.setStyleSheet("background:transparent;")

        # 创建Live2D部件
        self.live2d_widget = Live2DWidget(r"./recourse/mianfeimox/llny.model3.json")
        self.setCentralWidget(self.live2d_widget)

        #
        # # 窗口尺寸
        self.resize(800, 600)

        # 示例参数控制
        # QTimer.singleShot(1000, self.init_extra_controls)

    def init_extra_controls(self):
        # 初始化后控制示例
        if self.live2d_widget.model:
            # 设置透明度
            part_ids = self.live2d_widget.model.GetPartIds()
            if "PartHairBack" in part_ids:
                index = part_ids.index("PartHairBack")
                self.live2d_widget.model.SetPartOpacity(index, 0.7)

            # 控制嘴部
            self.live2d_widget.model.SetParameterValue(
                StandardParams.ParamMouthOpenY,
                0.5,
                1.0
            )

    def closeEvent(self, event):
        # 清理资源
        if self.live2d_widget.model:
            self.live2d_widget.model = None
        live2d.dispose()
        event.accept()


if __name__ == "__main__":
    # 配置OpenGL格式
    fmt = QSurfaceFormat()
    fmt.setVersion(3, 3)
    fmt.setProfile(QSurfaceFormat.CoreProfile)
    fmt.setAlphaBufferSize(8)
    QSurfaceFormat.setDefaultFormat(fmt)

    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())

**Comment by gyl1314** [comment]
> 方便发一下完整代码吗
方便

import os
import sys
from typing import Optional

from OpenGL.raw.GL.VERSION.GL_1_0 import glEnable, GL_BLEND, glBlendFunc, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, \
    glClearColor, glClear, GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT, glViewport
from PySide6.QtCore import Qt, QTimer, QPoint
from PySide6.QtGui import QSurfaceFormat, QMouseEvent
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import QApplication, QMainWindow
import live2d.v3 as live2d
from live2d.v3.params import StandardParams



class Live2DWidget(QOpenGLWidget):
    def __init__(self, model_path: str):
        super().__init__()
        self.model_path = os.path.normpath(model_path)
        self.model: Optional[live2d.LAppModel] = None
        self.last_pos = QPoint()
        self.setAutoFillBackground(False)  # 在Live2DWidget构造函数中添加


        # OpenGL 高级配置

        fmt = QSurfaceFormat()
        fmt.setAlphaBufferSize(0)
        fmt.setSamples(4)
        self.setFormat(fmt)

        # 60FPS 定时器
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.update)
        self.timer.start(16)

    def initializeGL(self):
        # 核心透明通道初始化[6,7](@ref)
        glEnable(GL_BLEND)
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
        # glClearColor(1.0, 0.0, 0.0, 0.0)
        # live2d.clearBuffer()

        # Live2D 初始化
        live2d.init()
        live2d.glewInit()

        # 加载模型（增加异常处理）
        try:
            self.model = live2d.LAppModel()
            self.model.LoadModelJson(self.model_path)
            # 根据模型发布者或者模型 XXX.cdi3.json 中可查找到水印对应的参数 id

            # 假设查找到的模型参数 id 为 Param261，假设值为 0 表示显示水印，值为 1 表示消失
            self.model.SetParameterValue("Param14", 1, 1)
            # print(f"Part Count: {self.model.GetPartCount()}")
            # # 获取 part 名称的字符串数组
            # partIds = self.model.GetPartIds()
            # print(f"Part Ids: {partIds}")
            # # 设置部件 PartHairBack 的透明度为 50%
            # self.model.SetPartOpacity(partIds.index("PartHairBack"), 0.5)
            # self.model.SetPartOpacity(partIds.index("PartHairBack"), 0.5)
            self.model.Resize(self.width(), self.height())
        except Exception as e:
            print(f"模型加载失败: {str(e)}")
            QApplication.instance().quit()

    def paintGL(self):

        # glClearColor(0.0, 0.0, 0.0, 0.0)
        # glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)  # 关键修复点[1,6](@ref)
        # glClear(GL_COLOR_BUFFER_BIT)
        live2d.clearBuffer()
        if self.model:
            self.model.Update()
            self.model.Draw()

    def resizeGL(self, w: int, h: int):
        glViewport(0, 0, w, h)
        if self.model:
            self.model.Resize(w, h)
class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Live2D透明窗口")

        # 配置主窗口透明
        self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground)
        self.setWindowFlag(Qt.WindowType.FramelessWindowHint)
        # self.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)

        self.setStyleSheet("background:transparent;")

        # 创建Live2D部件
        self.live2d_widget = Live2DWidget(r"./recourse/mianfeimox/llny.model3.json")
        self.setCentralWidget(self.live2d_widget)

        #
        # # 窗口尺寸
        self.resize(800, 600)

        # 示例参数控制
        # QTimer.singleShot(1000, self.init_extra_controls)

    def init_extra_controls(self):
        # 初始化后控制示例
        if self.live2d_widget.model:
            # 设置透明度
            part_ids = self.live2d_widget.model.GetPartIds()
            if "PartHairBack" in part_ids:
                index = part_ids.index("PartHairBack")
                self.live2d_widget.model.SetPartOpacity(index, 0.7)

            # 控制嘴部
            self.live2d_widget.model.SetParameterValue(
                StandardParams.ParamMouthOpenY,
                0.5,
                1.0
            )

    def closeEvent(self, event):
        # 清理资源
        if self.live2d_widget.model:
            self.live2d_widget.model = None
        live2d.dispose()
        event.accept()


if __name__ == "__main__":
    # 配置OpenGL格式
    fmt = QSurfaceFormat()
    fmt.setVersion(3, 3)
    fmt.setProfile(QSurfaceFormat.CoreProfile)
    fmt.setAlphaBufferSize(8)
    QSurfaceFormat.setDefaultFormat(fmt)

    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
